### ISSUE TITLE
ZAT giving warning.

### ISSUE THREAD

**Issue by rajanmagar** [evoko/zendesk-theme#30]
@rottbers I tried `zat theme preview` but it is giving warnings.

**Comment by rottbers** [comment]
Hey @rajanmagar, I'm not actively working on this project so my memory is a bit foggy. Anyhow if I recall correctly you need to have ZAT setup, this article could perhaps be a good start: https://support.zendesk.com/hc/en-us/articles/115012793547

Anyhow I will close this issue but if you're working on a theme of your own and need help then I suggest contacting Zendesk directly. Best of luck!
